- app/api/auth.py
- app/core/auth.py
- app/db/crud/users.py
> :update: integrated signup for ergoauth

- README.md
- app/api/activities.py
- app/api/dao.py
- app/api/util.py
- app/db/crud/activity_log.py
- app/db/crud/dao.py
- app/db/models/activity_log.py
- app/db/schemas/activity.py
- app/main.py
- app/test/test_example.py
- get activities by user_id - `GET /api/activities/{user_id}`
- create activity for user_id - `POST /api/activities/{user_id}`
- delete activity by id - `DELETE /api/activites/{id}`
- https://github.com/ergo-pad/ergopad-api/issues/359
```python
class CreateOrUpdateActivity(BaseModel):
user_id: int
img_url: t.Optional[str]
action: t.Optional[str]
value: t.Optional[str]
secondary_action: t.Optional[str]
secondary_value: t.Optional[str]
category: t.Optional[str]
class Activity(CreateOrUpdateActivity):
id: int
date: datetime.datetime
class Config:
orm_mode = True
```
> :add: api/activities

- app/api/notifications.py
- app/api/proposals.py
- app/db/crud/notifications.py
- app/db/models/notifications.py
- app/db/schemas/notifications.py
- app/main.py
```python
@r.get(
"/{user_id}",
response_model=t.List[Notification],
response_model_exclude_none=True,
name="notifications:all-notifications"
)
@r.post("/{user_id}", response_model=Notification, response_model_exclude_none=True, name="notifications:create")
async def notification_create(
user_id: int,
notification: CreateAndUpdateNotification,
db=Depends(get_db),
current_user=Depends(get_current_active_superuser),
)
@r.put("/mark_as_read/{notification_id}", response_model=Notification, response_model_exclude_none=True, name="notifications:read")
def notification_edit(
notification_id: int,
db=Depends(get_db),
current_user=Depends(get_current_active_user),
)
@r.delete(
"/clean_up", name="notifications:clean-up"
)
def notification_cleanup(
db=Depends(get_db), …
```
> :add: notifications api

- app/api/auth.py
- app/api/users.py
- app/core/auth.py
- app/db/crud/dao.py
- app/db/crud/proposals.py
- app/db/crud/users.py
- app/db/models/governance.py
- app/db/models/tokenomics.py
- app/db/models/users.py
- app/db/schemas/dao.py
- app/db/schemas/ergoauth.py
- app/db/schemas/users.py
- app/main.py
```
interface UserAddressConfig {
id: int;
alias: str;	// this is primary wallet address for non admin users
registered_addresses: t.List[str]	// list of addresses the users has been verified for
}
```
Instead of the current flow, LoginRequest will always take a list of addresses.
```
LoginRequest:
addresses: t.List[str]
```
- For new users, the first address is taken as default and we proceed with ergo-auth with the address at index 0.
- For mobile users the list should only have one address.
- For existing users we find out what their user id is from the list of addresses and the information we have in our database. We use the primary address already set to proceed with login.
```
PrimaryAddressChangeRequest:
address: str
```
For primary address change, we first make sure that the user …
> :update: user details rebase

- app/db/crud/users.py
- app/db/schemas/users.py
Add jwt token creation when changing an address.
> User address change jwt token fix

- app/db/crud/users.py
- app/db/schemas/users.py
Reverts ergo-pad/paideia-api#13
> Revert "User address change jwt token fix"

- app/api/users.py
- app/db/crud/users.py
- app/db/schemas/users.py
When changing a user's wallet address, a new JWT should be assigned to the new address. Correct placement in /api
> JWT token fix on user update

- app/api/auth.py
- app/db/crud/proposals.py
- app/db/schemas/proposal.py
- Add user alias when querying comments.
- Add metadata for references
- Name
- Status (if proposal, pull from on chain)
- Likes
- Dislikes
- Img
> Comment & References Metadata

- app/api/dao.py
- app/api/proposals.py
- app/db/crud/dao.py
- app/db/crud/proposals.py
- app/db/models/proposals.py
- app/db/models/tokenomics.py
- app/db/schemas/dao.py
- app/db/schemas/proposal.py
- Issue https://github.com/ergo-pad/paideia/issues/4
- Adds status to proposal table (https://github.com/ergo-pad/paideia-data/commit/f40c07a1dab5e12a5dd8db80e6509164a73347c2)
- Adds token_id field to tokenomics (https://github.com/ergo-pad/paideia-data/commit/fb199945d86bee7d6128b907fc0addaf215042f7)
- GET daos by dao_url. Example: `/api/dao/paideia`, `/api/dao/ergolend`
> :update: fixes for prod readiness

- app/api/proposals.py
- app/db/crud/proposals.py
- app/db/models/proposals.py
- app/db/schemas/proposal.py
- websocket endpoint only returns last comment instead of entire list of comments
- adds likes and dislikes support for individual comments
- sql change: https://github.com/ergo-pad/paideia-data/commit/d674bfd30884bec2783fb72ad9a4c2721d9d601e
- https://github.com/ergo-pad/paideia/issues/4
> :update: proposal comments

- app/api/auth.py
- app/api/users.py
- app/db/crud/users.py
- app/db/schemas/users.py
- Required changes for https://github.com/ergo-pad/ergopad-api/issues/494
> Removes hardcoded local ips

- app/api/auth.py
Added profile image to comments on get.
> Comments w/ Images

- app/db/crud/users.py
> :fix: login issue

- app/api/activities.py
- app/api/proposals.py
- app/db/crud/activity_log.py
- app/db/crud/proposals.py
- app/db/schemas/activity.py
- Issue: https://github.com/ergo-pad/ergopad-api/issues/499
> :add: activity logging for discusssions

- app/api/activities.py
- app/api/notifications.py
- app/api/proposals.py
- app/core/async_handler.py
- app/db/crud/notifications.py
- app/db/schemas/notifications.py
- https://github.com/ergo-pad/ergopad-api/issues/499
> :add: notifications hook

- app/api/proposals.py
- app/db/crud/proposals.py
> :add: GET proposals/by_user_details_id

- app/api/blogs.py
- app/db/crud/blogs.py
- app/db/models/blogs.py
- app/db/schemas/blog.py
- app/main.py
```json
{
"name": "string",
"img_url": "string",
"description": "string",
"content": "string",
"category": "string",
"additional_details": {
"add_to_highlights": false,
"add_to_education_page": false
},
"id": 0,
"link": "string",
"date": "2022-10-13T16:49:33.131Z"
}
```
- GET `/blogs/?search_string={name}&highlights_only={bool}&education_only={bool}`
- GET `/blogs/{link}`
- POST `/blogs/`
- PUT `/blogs/{id}`
- DELETE `/blogs/{id}`
> :add: blogs cms

- app/db/crud/activity_log.py
- app/db/crud/proposals.py
- app/db/crud/users.py
- app/db/models/activity_log.py
- app/db/schemas/activity.py
- app/db/schemas/users.py
> :fix: bugs and patch api

- app/api/faq.py
- app/api/quotes.py
- app/db/crud/faqs.py
- app/db/crud/quotes.py
- app/db/models/faqs.py
- app/db/models/quotes.py
- app/db/schemas/faq.py
- app/db/schemas/quote.py
- app/main.py
- basic CRUD
- database schema changes -> https://github.com/ergo-pad/paideia-data/commit/aa216fb405be3764e2aefa22882b3b6ea126d17e
- issue link -> https://github.com/ergo-pad/ergopad-api/issues/511
> :add: cms for faq and quotes

- app/db/crud/dao.py
- app/db/schemas/dao.py
- update schemas for daos
- add default values where applicable
- resolve dao deletion bug
> :fix: dao api issues

- app/api/activities.py
- app/api/users.py
- app/db/crud/activity_log.py
- app/db/crud/dao.py
- app/db/schemas/proposal.py
> :update: various bug fixes

- app/api/util.py
- app/requirements.txt
- app/util/image_optimizer.py
Issue - https://github.com/ergo-pad/ergopad-api/issues/574
- `/api/util/upload_image/{compression_type}`
> :add: image scaling endpoint

- Dockerfile
- app/db/crud/dao.py
- app/db/models/dao.py
- app/db/schemas/dao.py
Required for paideia.im/projects page
> Adds Dao Description to vw_dao

- app/api/proposals.py
- app/db/crud/proposals.py
- app/db/schemas/activity.py
- app/db/schemas/proposal.py
API changes for Issue - https://github.com/ergo-pad/ergopad-api/issues/573
> Adds ability for users to delete their comments

- app/api/assets.py
- app/api/users.py
- app/db/crud/proposals.py
- app/db/crud/users.py
- app/util/util.py
> :add: get slug api for users and proposals

- app/api/assets.py
Handles all membership checks in a single endpoint. Moving forward, suggest we pull the config file from the database so it's dynamic with new daos that are created.
> Dao Membership Refactor

- app/api/assets.py
Issue - https://github.com/ergo-pad/paideia-frontend/issues/81
> :add: dao_membership endpoint

- app/api/assets.py
- fixes issues related to https://github.com/ergo-pad/paideia-frontend/issues/81
> :update: locked tokens to new request schema

- app/db/crud/users.py
- app/db/schemas/__init__.py
- app/db/schemas/dao.py
- app/db/schemas/users.py
- https://github.com/ergo-pad/ergopad-api/issues/592
- Introduces `RestrictedAlphabetStr` class
> :add: get users by dao-username slugs

- app/api/util.py
> :fix: markdown image response format

- app/api/util.py
- app/aws/s3.py
- app/config.py
> :fix: s3 upload

- app/api/assets.py
- app/ergo/schemas.py
> :add: token-exists pass through

- app/ergo/token_data_provider.py
> :fix: token stats provider

- app/ergo/schemas.py
- app/ergo/token_data_provider.py
> :fix: null values in TokenStats
